// Country data with populations over 21,000
const countryData = [
   // Major countries (top 30 by population)
   { name: { common: "China" }, population: 1402112000, flags: { png: "https://flagcdn.com/w320/cn.png" } },
   { name: { common: "India" }, population: 1380004385, flags: { png: "https://flagcdn.com/w320/in.png" } },
   { name: { common: "United States" }, population: 331002651, flags: { png: "https://flagcdn.com/w320/us.png" } },
   { name: { common: "Indonesia" }, population: 273523615, flags: { png: "https://flagcdn.com/w320/id.png" } },
   { name: { common: "Pakistan" }, population: 220892340, flags: { png: "https://flagcdn.com/w320/pk.png" } },
   { name: { common: "Brazil" }, population: 212559417, flags: { png: "https://flagcdn.com/w320/br.png" } },
   { name: { common: "Nigeria" }, population: 206139589, flags: { png: "https://flagcdn.com/w320/ng.png" } },
   { name: { common: "Bangladesh" }, population: 164689383, flags: { png: "https://flagcdn.com/w320/bd.png" } },
   { name: { common: "Russia" }, population: 144104080, flags: { png: "https://flagcdn.com/w320/ru.png" } },
   { name: { common: "Mexico" }, population: 128932753, flags: { png: "https://flagcdn.com/w320/mx.png" } },
   { name: { common: "Japan" }, population: 125836021, flags: { png: "https://flagcdn.com/w320/jp.png" } },
   { name: { common: "Ethiopia" }, population: 114963588, flags: { png: "https://flagcdn.com/w320/et.png" } },
   { name: { common: "Philippines" }, population: 109581078, flags: { png: "https://flagcdn.com/w320/ph.png" } },
   { name: { common: "Egypt" }, population: 102334404, flags: { png: "https://flagcdn.com/w320/eg.png" } },
   { name: { common: "Vietnam" }, population: 97338579, flags: { png: "https://flagcdn.com/w320/vn.png" } },
   { name: { common: "DR Congo" }, population: 89561403, flags: { png: "https://flagcdn.com/w320/cd.png" } },
   { name: { common: "Turkey" }, population: 84339067, flags: { png: "https://flagcdn.com/w320/tr.png" } },
   { name: { common: "Iran" }, population: 83992949, flags: { png: "https://flagcdn.com/w320/ir.png" } },
   { name: { common: "Germany" }, population: 83240525, flags: { png: "https://flagcdn.com/w320/de.png" } },
   { name: { common: "Thailand" }, population: 69799978, flags: { png: "https://flagcdn.com/w320/th.png" } },
   { name: { common: "United Kingdom" }, population: 67215293, flags: { png: "https://flagcdn.com/w320/gb.png" } },
   { name: { common: "France" }, population: 65273511, flags: { png: "https://flagcdn.com/w320/fr.png" } },
   { name: { common: "Italy" }, population: 59554023, flags: { png: "https://flagcdn.com/w320/it.png" } },
   { name: { common: "Tanzania" }, population: 59734218, flags: { png: "https://flagcdn.com/w320/tz.png" } },
   { name: { common: "South Africa" }, population: 59308690, flags: { png: "https://flagcdn.com/w320/za.png" } },
   { name: { common: "Myanmar" }, population: 54409800, flags: { png: "https://flagcdn.com/w320/mm.png" } },
   { name: { common: "Kenya" }, population: 53771296, flags: { png: "https://flagcdn.com/w320/ke.png" } },
   { name: { common: "South Korea" }, population: 51269185, flags: { png: "https://flagcdn.com/w320/kr.png" } },
   { name: { common: "Colombia" }, population: 50882891, flags: { png: "https://flagcdn.com/w320/co.png" } },
   { name: { common: "Spain" }, population: 46754778, flags: { png: "https://flagcdn.com/w320/es.png" } },

   // Medium-sized countries
   { name: { common: "Uganda" }, population: 45741007, flags: { png: "https://flagcdn.com/w320/ug.png" } },
   { name: { common: "Argentina" }, population: 45195774, flags: { png: "https://flagcdn.com/w320/ar.png" } },
   { name: { common: "Algeria" }, population: 44616624, flags: { png: "https://flagcdn.com/w320/dz.png" } },
   { name: { common: "Sudan" }, population: 43849260, flags: { png: "https://flagcdn.com/w320/sd.png" } },
   { name: { common: "Ukraine" }, population: 44134693, flags: { png: "https://flagcdn.com/w320/ua.png" } },
   { name: { common: "Iraq" }, population: 40222493, flags: { png: "https://flagcdn.com/w320/iq.png" } },
   { name: { common: "Afghanistan" }, population: 38928346, flags: { png: "https://flagcdn.com/w320/af.png" } },
   { name: { common: "Poland" }, population: 37846611, flags: { png: "https://flagcdn.com/w320/pl.png" } },
   { name: { common: "Canada" }, population: 38005238, flags: { png: "https://flagcdn.com/w320/ca.png" } },
   { name: { common: "Morocco" }, population: 36910560, flags: { png: "https://flagcdn.com/w320/ma.png" } },
   { name: { common: "Saudi Arabia" }, population: 34813871, flags: { png: "https://flagcdn.com/w320/sa.png" } },
   { name: { common: "Uzbekistan" }, population: 33469203, flags: { png: "https://flagcdn.com/w320/uz.png" } },
   { name: { common: "Peru" }, population: 32971854, flags: { png: "https://flagcdn.com/w320/pe.png" } },
   { name: { common: "Malaysia" }, population: 32365999, flags: { png: "https://flagcdn.com/w320/my.png" } },
   { name: { common: "Angola" }, population: 32866272, flags: { png: "https://flagcdn.com/w320/ao.png" } },
   { name: { common: "Mozambique" }, population: 31255435, flags: { png: "https://flagcdn.com/w320/mz.png" } },
   { name: { common: "Ghana" }, population: 31072940, flags: { png: "https://flagcdn.com/w320/gh.png" } },
   { name: { common: "Yemen" }, population: 29825964, flags: { png: "https://flagcdn.com/w320/ye.png" } },
   { name: { common: "Nepal" }, population: 29136808, flags: { png: "https://flagcdn.com/w320/np.png" } },
   { name: { common: "Venezuela" }, population: 28435940, flags: { png: "https://flagcdn.com/w320/ve.png" } },

   // Smaller countries but still significant population
   { name: { common: "Madagascar" }, population: 27691018, flags: { png: "https://flagcdn.com/w320/mg.png" } },
   { name: { common: "Cameroon" }, population: 26545863, flags: { png: "https://flagcdn.com/w320/cm.png" } },
   { name: { common: "Ivory Coast" }, population: 26378274, flags: { png: "https://flagcdn.com/w320/ci.png" } },
   { name: { common: "North Korea" }, population: 25778816, flags: { png: "https://flagcdn.com/w320/kp.png" } },
   { name: { common: "Australia" }, population: 25499884, flags: { png: "https://flagcdn.com/w320/au.png" } },
   { name: { common: "Niger" }, population: 24206644, flags: { png: "https://flagcdn.com/w320/ne.png" } },
   { name: { common: "Taiwan" }, population: 23816775, flags: { png: "https://flagcdn.com/w320/tw.png" } },
   { name: { common: "Sri Lanka" }, population: 21919000, flags: { png: "https://flagcdn.com/w320/lk.png" } },
   { name: { common: "Burkina Faso" }, population: 20903273, flags: { png: "https://flagcdn.com/w320/bf.png" } },
   { name: { common: "Mali" }, population: 20250833, flags: { png: "https://flagcdn.com/w320/ml.png" } },
   { name: { common: "Romania" }, population: 19237691, flags: { png: "https://flagcdn.com/w320/ro.png" } },
   { name: { common: "Malawi" }, population: 19129952, flags: { png: "https://flagcdn.com/w320/mw.png" } },
   { name: { common: "Chile" }, population: 19116201, flags: { png: "https://flagcdn.com/w320/cl.png" } },
   { name: { common: "Kazakhstan" }, population: 18754440, flags: { png: "https://flagcdn.com/w320/kz.png" } },
   { name: { common: "Zambia" }, population: 18383955, flags: { png: "https://flagcdn.com/w320/zm.png" } },
   { name: { common: "Guatemala" }, population: 16858333, flags: { png: "https://flagcdn.com/w320/gt.png" } },
   { name: { common: "Ecuador" }, population: 17643054, flags: { png: "https://flagcdn.com/w320/ec.png" } },
   { name: { common: "Syria" }, population: 17500658, flags: { png: "https://flagcdn.com/w320/sy.png" } },
   { name: { common: "Netherlands" }, population: 17134872, flags: { png: "https://flagcdn.com/w320/nl.png" } },
   { name: { common: "Senegal" }, population: 16743927, flags: { png: "https://flagcdn.com/w320/sn.png" } },
   { name: { common: "Cambodia" }, population: 16718965, flags: { png: "https://flagcdn.com/w320/kh.png" } },
   { name: { common: "Chad" }, population: 16425864, flags: { png: "https://flagcdn.com/w320/td.png" } },
   { name: { common: "Somalia" }, population: 15893222, flags: { png: "https://flagcdn.com/w320/so.png" } },
   { name: { common: "Zimbabwe" }, population: 14862924, flags: { png: "https://flagcdn.com/w320/zw.png" } },
   { name: { common: "Guinea" }, population: 13132795, flags: { png: "https://flagcdn.com/w320/gn.png" } },
   { name: { common: "Rwanda" }, population: 12952218, flags: { png: "https://flagcdn.com/w320/rw.png" } },
   { name: { common: "Benin" }, population: 12123200, flags: { png: "https://flagcdn.com/w320/bj.png" } },
   { name: { common: "Burundi" }, population: 11890784, flags: { png: "https://flagcdn.com/w320/bi.png" } },
   { name: { common: "Tunisia" }, population: 11818619, flags: { png: "https://flagcdn.com/w320/tn.png" } },
   { name: { common: "Bolivia" }, population: 11673021, flags: { png: "https://flagcdn.com/w320/bo.png" } },
   { name: { common: "Belgium" }, population: 11555997, flags: { png: "https://flagcdn.com/w320/be.png" } },
   { name: { common: "Haiti" }, population: 11402528, flags: { png: "https://flagcdn.com/w320/ht.png" } },
   { name: { common: "Cuba" }, population: 11326616, flags: { png: "https://flagcdn.com/w320/cu.png" } },
   { name: { common: "South Sudan" }, population: 11193725, flags: { png: "https://flagcdn.com/w320/ss.png" } },
   { name: { common: "Dominican Republic" }, population: 10847910, flags: { png: "https://flagcdn.com/w320/do.png" } },
   { name: { common: "Czech Republic" }, population: 10708981, flags: { png: "https://flagcdn.com/w320/cz.png" } },
   { name: { common: "Greece" }, population: 10423054, flags: { png: "https://flagcdn.com/w320/gr.png" } },
   { name: { common: "Jordan" }, population: 10203134, flags: { png: "https://flagcdn.com/w320/jo.png" } },
   { name: { common: "Portugal" }, population: 10196709, flags: { png: "https://flagcdn.com/w320/pt.png" } },
   { name: { common: "Azerbaijan" }, population: 10139177, flags: { png: "https://flagcdn.com/w320/az.png" } },
   { name: { common: "Sweden" }, population: 10099265, flags: { png: "https://flagcdn.com/w320/se.png" } },
   { name: { common: "Honduras" }, population: 9904607, flags: { png: "https://flagcdn.com/w320/hn.png" } },
   { name: { common: "United Arab Emirates" }, population: 9890402, flags: { png: "https://flagcdn.com/w320/ae.png" } },
   { name: { common: "Hungary" }, population: 9660351, flags: { png: "https://flagcdn.com/w320/hu.png" } },
   { name: { common: "Tajikistan" }, population: 9537645, flags: { png: "https://flagcdn.com/w320/tj.png" } },
   { name: { common: "Belarus" }, population: 9449323, flags: { png: "https://flagcdn.com/w320/by.png" } },
   { name: { common: "Austria" }, population: 8917205, flags: { png: "https://flagcdn.com/w320/at.png" } },
   { name: { common: "Papua New Guinea" }, population: 8947024, flags: { png: "https://flagcdn.com/w320/pg.png" } },
   { name: { common: "Serbia" }, population: 6908224, flags: { png: "https://flagcdn.com/w320/rs.png" } },
   { name: { common: "Israel" }, population: 9216900, flags: { png: "https://flagcdn.com/w320/il.png" } },
   { name: { common: "Switzerland" }, population: 8654622, flags: { png: "https://flagcdn.com/w320/ch.png" } },
   { name: { common: "Togo" }, population: 8278724, flags: { png: "https://flagcdn.com/w320/tg.png" } },
   { name: { common: "Sierra Leone" }, population: 7976983, flags: { png: "https://flagcdn.com/w320/sl.png" } },
   { name: { common: "Hong Kong" }, population: 7481800, flags: { png: "https://flagcdn.com/w320/hk.png" } },
   { name: { common: "Laos" }, population: 7275560, flags: { png: "https://flagcdn.com/w320/la.png" } },
   { name: { common: "Paraguay" }, population: 7132538, flags: { png: "https://flagcdn.com/w320/py.png" } },
   { name: { common: "Bulgaria" }, population: 6948445, flags: { png: "https://flagcdn.com/w320/bg.png" } },
   { name: { common: "Libya" }, population: 6871292, flags: { png: "https://flagcdn.com/w320/ly.png" } },
   { name: { common: "Lebanon" }, population: 6825445, flags: { png: "https://flagcdn.com/w320/lb.png" } },
   { name: { common: "Nicaragua" }, population: 6624554, flags: { png: "https://flagcdn.com/w320/ni.png" } },
   { name: { common: "Kyrgyzstan" }, population: 6524195, flags: { png: "https://flagcdn.com/w320/kg.png" } },
   { name: { common: "El Salvador" }, population: 6486205, flags: { png: "https://flagcdn.com/w320/sv.png" } },
   { name: { common: "Turkmenistan" }, population: 6031200, flags: { png: "https://flagcdn.com/w320/tm.png" } },
   { name: { common: "Singapore" }, population: 5685807, flags: { png: "https://flagcdn.com/w320/sg.png" } },
   { name: { common: "Denmark" }, population: 5831404, flags: { png: "https://flagcdn.com/w320/dk.png" } },
   { name: { common: "Finland" }, population: 5530719, flags: { png: "https://flagcdn.com/w320/fi.png" } },
   { name: { common: "Slovakia" }, population: 5458827, flags: { png: "https://flagcdn.com/w320/sk.png" } },
   { name: { common: "Norway" }, population: 5379475, flags: { png: "https://flagcdn.com/w320/no.png" } },
   { name: { common: "Oman" }, population: 5106626, flags: { png: "https://flagcdn.com/w320/om.png" } },
   { name: { common: "Palestine" }, population: 4803269, flags: { png: "https://flagcdn.com/w320/ps.png" } },
   { name: { common: "Costa Rica" }, population: 5094118, flags: { png: "https://flagcdn.com/w320/cr.png" } },
   { name: { common: "Ireland" }, population: 4937786, flags: { png: "https://flagcdn.com/w320/ie.png" } },
   { name: { common: "New Zealand" }, population: 4822233, flags: { png: "https://flagcdn.com/w320/nz.png" } },
   { name: { common: "Liberia" }, population: 5057681, flags: { png: "https://flagcdn.com/w320/lr.png" } },
   { name: { common: "Kuwait" }, population: 4270571, flags: { png: "https://flagcdn.com/w320/kw.png" } },
   { name: { common: "Panama" }, population: 4314767, flags: { png: "https://flagcdn.com/w320/pa.png" } },
   { name: { common: "Mauritania" }, population: 4649658, flags: { png: "https://flagcdn.com/w320/mr.png" } },
   { name: { common: "Croatia" }, population: 4105267, flags: { png: "https://flagcdn.com/w320/hr.png" } },
   { name: { common: "Georgia" }, population: 3720400, flags: { png: "https://flagcdn.com/w320/ge.png" } },
   { name: { common: "Eritrea" }, population: 3546421, flags: { png: "https://flagcdn.com/w320/er.png" } },
   { name: { common: "Uruguay" }, population: 3473730, flags: { png: "https://flagcdn.com/w320/uy.png" } },
   { name: { common: "Mongolia" }, population: 3278290, flags: { png: "https://flagcdn.com/w320/mn.png" } },
   { name: { common: "Bosnia and Herzegovina" }, population: 3280819, flags: { png: "https://flagcdn.com/w320/ba.png" } },
   { name: { common: "Jamaica" }, population: 2961167, flags: { png: "https://flagcdn.com/w320/jm.png" } },
   { name: { common: "Qatar" }, population: 2881053, flags: { png: "https://flagcdn.com/w320/qa.png" } },
   { name: { common: "Albania" }, population: 2837743, flags: { png: "https://flagcdn.com/w320/al.png" } },
   { name: { common: "Armenia" }, population: 2963243, flags: { png: "https://flagcdn.com/w320/am.png" } },
   { name: { common: "Lithuania" }, population: 2722289, flags: { png: "https://flagcdn.com/w320/lt.png" } },
   { name: { common: "Namibia" }, population: 2540905, flags: { png: "https://flagcdn.com/w320/na.png" } },
   { name: { common: "Gambia" }, population: 2416668, flags: { png: "https://flagcdn.com/w320/gm.png" } },
   { name: { common: "Botswana" }, population: 2351627, flags: { png: "https://flagcdn.com/w320/bw.png" } },
   { name: { common: "Gabon" }, population: 2225734, flags: { png: "https://flagcdn.com/w320/ga.png" } },
   { name: { common: "Slovenia" }, population: 2078938, flags: { png: "https://flagcdn.com/w320/si.png" } },
   { name: { common: "North Macedonia" }, population: 2083374, flags: { png: "https://flagcdn.com/w320/mk.png" } },
   { name: { common: "Lesotho" }, population: 2142249, flags: { png: "https://flagcdn.com/w320/ls.png" } },
   { name: { common: "Latvia" }, population: 1901548, flags: { png: "https://flagcdn.com/w320/lv.png" } },
   { name: { common: "Kosovo" }, population: 1873000, flags: { png: "https://flagcdn.com/w320/xk.png" } },
   { name: { common: "Bahrain" }, population: 1701575, flags: { png: "https://flagcdn.com/w320/bh.png" } },
   { name: { common: "Equatorial Guinea" }, population: 1402985, flags: { png: "https://flagcdn.com/w320/gq.png" } },
   { name: { common: "Trinidad and Tobago" }, population: 1399488, flags: { png: "https://flagcdn.com/w320/tt.png" } },
   { name: { common: "Estonia" }, population: 1331057, flags: { png: "https://flagcdn.com/w320/ee.png" } },
   { name: { common: "Mauritius" }, population: 1265740, flags: { png: "https://flagcdn.com/w320/mu.png" } },
   { name: { common: "Cyprus" }, population: 1207359, flags: { png: "https://flagcdn.com/w320/cy.png" } },
   { name: { common: "Eswatini" }, population: 1160164, flags: { png: "https://flagcdn.com/w320/sz.png" } },
   { name: { common: "Djibouti" }, population: 988000, flags: { png: "https://flagcdn.com/w320/dj.png" } },
   { name: { common: "Fiji" }, population: 896445, flags: { png: "https://flagcdn.com/w320/fj.png" } },
   { name: { common: "Comoros" }, population: 869601, flags: { png: "https://flagcdn.com/w320/km.png" } },
   { name: { common: "Guyana" }, population: 786552, flags: { png: "https://flagcdn.com/w320/gy.png" } },
   { name: { common: "Bhutan" }, population: 771608, flags: { png: "https://flagcdn.com/w320/bt.png" } },
   { name: { common: "Solomon Islands" }, population: 686884, flags: { png: "https://flagcdn.com/w320/sb.png" } },
   { name: { common: "Montenegro" }, population: 621718, flags: { png: "https://flagcdn.com/w320/me.png" } },
   { name: { common: "Luxembourg" }, population: 632275, flags: { png: "https://flagcdn.com/w320/lu.png" } },
   { name: { common: "Suriname" }, population: 586632, flags: { png: "https://flagcdn.com/w320/sr.png" } },
   { name: { common: "Cape Verde" }, population: 555987, flags: { png: "https://flagcdn.com/w320/cv.png" } },
   { name: { common: "Malta" }, population: 514564, flags: { png: "https://flagcdn.com/w320/mt.png" } },
   { name: { common: "Brunei" }, population: 437483, flags: { png: "https://flagcdn.com/w320/bn.png" } },
   { name: { common: "Belize" }, population: 397628, flags: { png: "https://flagcdn.com/w320/bz.png" } },
   { name: { common: "Bahamas" }, population: 393244, flags: { png: "https://flagcdn.com/w320/bs.png" } },
   { name: { common: "Maldives" }, population: 540544, flags: { png: "https://flagcdn.com/w320/mv.png" } },
   { name: { common: "Iceland" }, population: 366425, flags: { png: "https://flagcdn.com/w320/is.png" } },
   { name: { common: "Vanuatu" }, population: 307145, flags: { png: "https://flagcdn.com/w320/vu.png" } },
   { name: { common: "Barbados" }, population: 287375, flags: { png: "https://flagcdn.com/w320/bb.png" } },
   { name: { common: "Samoa" }, population: 198410, flags: { png: "https://flagcdn.com/w320/ws.png" } },
   { name: { common: "Saint Lucia" }, population: 183627, flags: { png: "https://flagcdn.com/w320/lc.png" } },
   { name: { common: "Kiribati" }, population: 119449, flags: { png: "https://flagcdn.com/w320/ki.png" } },
   { name: { common: "Grenada" }, population: 112523, flags: { png: "https://flagcdn.com/w320/gd.png" } },
   { name: { common: "Seychelles" }, population: 98347, flags: { png: "https://flagcdn.com/w320/sc.png" } },
   { name: { common: "Antigua and Barbuda" }, population: 97929, flags: { png: "https://flagcdn.com/w320/ag.png" } },
   { name: { common: "Andorra" }, population: 77265, flags: { png: "https://flagcdn.com/w320/ad.png" } },
   { name: { common: "Dominica" }, population: 71986, flags: { png: "https://flagcdn.com/w320/dm.png" } },
   { name: { common: "Marshall Islands" }, population: 59190, flags: { png: "https://flagcdn.com/w320/mh.png" } },
   { name: { common: "Saint Kitts and Nevis" }, population: 53199, flags: { png: "https://flagcdn.com/w320/kn.png" } },
   { name: { common: "Monaco" }, population: 39242, flags: { png: "https://flagcdn.com/w320/mc.png" } },
   { name: { common: "Liechtenstein" }, population: 38128, flags: { png: "https://flagcdn.com/w320/li.png" } },
   { name: { common: "San Marino" }, population: 33938, flags: { png: "https://flagcdn.com/w320/sm.png" } },
   { name: { common: "Palau" }, population: 18094, flags: { png: "https://flagcdn.com/w320/pw.png" } },
   { name: { common: "Nauru" }, population: 10834, flags: { png: "https://flagcdn.com/w320/nr.png" } },
   { name: { common: "Tuvalu" }, population: 11792, flags: { png: "https://flagcdn.com/w320/tv.png" } }
];